user:
  name: some_name

users:
  personal:
    name: personal
  work:
    name: work

screen:
  dpi: 128
  scale: 1.33333333

video: intel

font:
  sans:
    family: PT Sans
    size: 10
  monospace:
    family: PT Mono
    size: 9

# screen:
#   dpi: 120
#   scale: 1.25

# screen:
#   dpi: 144
#   scale: 1.5
