users:
  - name: personal
    groups: wheel,docker
  - name: work
    groups: docker

screen:
  dpi: 120
  scale: 1.25

video: intel
# video: amd

system_partition: sda3

battery: true

backlight: true

font:
  sans:
    family: Fira Sans
    size: 11
  monospace:
    family: Fantasque Sans Mono
    size: 12
# screen:
#   dpi: 128
#   scale: 1.33333333

# screen:
#   dpi: 120
#   scale: 1.25

# screen:
#   dpi: 144
#   scale: 1.5
