---
- name: create vim plug directory
  become_user: "{{ user.name }}"
  file:
    path: "/home/{{ user.name }}/.local/share/nvim/site/autoload"
    state: directory

- name: download vim plug
  become_user: "{{ user.name }}"
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "/home/{{ user.name }}/.local/share/nvim/site/autoload/plug.vim"

