---
- hosts: localhost
  tasks:
    # clock
    - name: set up the clock
      command: timedatectl set-ntp true

    # partitioning
    - name: wipe all on the disk
      command: sgdisk -Z /dev/sda
    # creating partitions
    - name: create new partition table
      command: sgdisk -a 2048 -o /dev/sda
    - name: create boot partition
      command: sgdisk -n 1:0:+512M /dev/sda
    - name: create swap partition
      command: sgdisk -n 2:0:+2G /dev/sda
    - name: create main partition
      command: sgdisk -n 3:0:0 /dev/sda
    # setting partition types
    - name: set boot partition type
      command: sgdisk -t 1:ef00 /dev/sda
    - name: set swap partition type
      command: sgdisk -t 2:8200 /dev/sda
    - name: set main partition type
      command: sgdisk -t 3:8300 /dev/sda

    # formatting paritions
    - name: format boot partition
      command: mkfs.vfat /dev/sda1
    - name: format swap partition
      command: mkswap /dev/sda2
    - name: format main partition
      command: mkfs.ext4 /dev/sda3
    - name: enable swap
      command: swapon /dev/sda2

    # mounting
    - name: mount main partition
      command: mount /dev/sda3 /mnt
    - name: create boot dir
      command: mkdir /mnt/boot
    - name: mount boot
      command: mount /dev/sda1 /mnt/boot

    # setting repository mirror
    - name: set repository mirror
      command: echo Server = http://mirror.datacenter.by/pub/archlinux/$repo/os/$arch >> /etc/pacman.d/mirrorlist

    # installing packages
    - name: install base packages
      command: pacstrap /mnt base ansible git

    # generating fstab
    - name: generate fstab
      command: genfstab -U /mnt >> /mnt/etc/fstab

    ### Post setup

    # - name: chroot into a system
