---
- hosts: localhost
  become: yes
  pre_tasks:
  roles:
    - { role: base }
    - { role: boot }
    - { role: dotfiles }
    - { role: locale }
    - { role: network }
    - { role: time }
    - { role: users }
    - { role: x11 }
