---
- hosts: localhost
  # become: yes
  pre_tasks:
    - pause:
        prompt: "Give root password"
      register: prompt
      no_log: yes
      run_once: yes
      when: "{{ lookup('env', 'INITIAL_LOAD') }}" != null
    - set_fact:
        username: "{{ prompt.user_input }}"
      no_log: yes
      run_once: yes
  roles:
    - { role: base }
    - { role: boot }
    - { role: network }
    - { role: time }
    - { role: locale }
