---
- hosts: localhost
  # become: yes
  pre_tasks:
    - set_fact: initial_load="{{ lookup('env', 'INITIAL_LOAD') }}"
    - pause:
        prompt: "Give user password"
        echo: no
      register: user_pass
      no_log: yes
      when: initial_load == True
    - set_fact: user_pass="{{ user_pass.user_input }}"
      when: initial_load == True
  roles:
    - { role: base }
    - { role: boot }
    - { role: fonts }
    - { role: interface }
    - { role: locale }
    - { role: network }
    - { role: terminals }
    - { role: time }
    - { role: users }
    - { role: xorg }
