# Directories
- name: create ~/Images
  become_user: "{{ user.name }}"
  file:
    path: "/home/{{ user.name }}/Images/"
    state: directory

- name: create ~/.config
  become_user: "{{ user.name }}"
  file:
    path: "/home/{{ user.name }}/.config/"
    state: directory

- name: create ~/.config/alacritty
  become_user: "{{ user.name }}"
  file:
    path: "/home/{{ user.name }}/.config/alacritty/"
    state: directory

- name: create ~/.config/gtk-3.0
  become_user: "{{ user.name }}"
  file:
    path: "/home/{{ user.name }}/.config/gtk-3.0/"
    state: directory

- name: create ~/.config/i3blocks
  become_user: "{{ user.name }}"
  file:
    path: "/home/{{ user.name }}/.config/i3blocks/"
    state: directory

- name: create ~/.config/i3blocks/scripts
  become_user: "{{ user.name }}"
  file:
    path: "/home/{{ user.name }}/.config/i3blocks/scripts"
    state: directory

- name: create ~/.config/nvim
  become_user: "{{ user.name }}"
  file:
    path: "/home/{{ user.name }}/.config/nvim/"
    state: directory

- name: create ~/.config/i3
  become_user: "{{ user.name }}"
  file:
    path: "/home/{{ user.name }}/.config/i3/"
    state: directory


# Files
- name: copy .xinitrc
  become_user: "{{ user.name }}"
  copy:
    src: .xinitrc
    dest: "/home/{{ user.name }}/.xinitrc"

- name: copy .inputrc
  become_user: "{{ user.name }}"
  copy:
    src: .inputrc
    dest: "/home/{{ user.name }}/.inputrc"

- name: copy .gtkrc-2.0
  become_user: "{{ user.name }}"
  copy:
    src: .gtkrc-2.0
    dest: "/home/{{ user.name }}/.gtkrc-2.0"

- name: copy gtk-3 settings.ini
  become_user: "{{ user.name }}"
  copy:
    src: .config/gtk-3.0/settings.ini
    dest: "/home/{{ user.name }}/.config/gtk-3.0/settings.ini"

- name: copy .config/i3blocks/config
  become_user: "{{ user.name }}"
  copy:
    src: .config/i3blocks/config
    dest: "/home/{{ user.name }}/.config/i3blocks/config"

- name: copy .config/i3blocks/scripts/battery
  become_user: "{{ user.name }}"
  copy:
    src: .config/i3blocks/scripts/battery
    dest: "/home/{{ user.name }}/.config/i3blocks/scripts/battery"
    mode: '0755'

- name: copy .config/i3blocks/scripts/keyboard
  become_user: "{{ user.name }}"
  copy:
    src: .config/i3blocks/scripts/keyboard
    dest: "/home/{{ user.name }}/.config/i3blocks/scripts/keyboard"
    mode: '0755'

- name: copy .config/nvim/init.vim
  become_user: "{{ user.name }}"
  copy:
    src: .config/nvim/init.vim
    dest: "/home/{{ user.name }}/.config/nvim/init.vim"

- name: copy wallpaper
  become_user: "{{ user.name }}"
  copy:
    src: Images/wallpaper.jpg
    dest: "/home/{{ user.name }}/Images/wallpaper.jpg"

- name: copy .Xresources
  become_user: "{{ user.name }}"
  template:
    src: .Xresources.j2
    dest: "/home/{{ user.name }}/.Xresources"

- name: copy .bashrc
  become_user: "{{ user.name }}"
  template:
    src: .bashrc.j2
    dest: "/home/{{ user.name }}/.bashrc"

- name: copy chromium-flags.conf
  become_user: "{{ user.name }}"
  template:
    src: .config/chromium-flags.conf.j2
    dest: "/home/{{ user.name }}/.config/chromium-flags.conf"

- name: copy i3 config
  become_user: "{{ user.name }}"
  template:
    src: .config/i3/config.j2
    dest: "/home/{{ user.name }}/.config/i3/config"

- name: copy .config/alacritty/alacritty.yml
  become_user: "{{ user.name }}"
  template:
    src: .config/alacritty/alacritty.yml.j2
    dest: "/home/{{ user.name }}/.config/alacritty/alacritty.yml"
