# Directories
- name: create ~/Images
  become_user: "{{ user.name }}"
  file:
    path: "/home/{{ user.name }}/Images/"
    state: directory

- name: create ~/.config
  become_user: "{{ user.name }}"
  file:
    path: "/home/{{ user.name }}/.config/"
    state: directory

- name: create ~/.config/alacritty
  become_user: "{{ user.name }}"
  file:
    path: "/home/{{ user.name }}/.config/alacritty/"
    state: directory

- name: create ~/.config/gtk-3.0
  become_user: "{{ user.name }}"
  file:
    path: "/home/{{ user.name }}/.config/gtk-3.0/"
    state: directory

- name: create ~/.config/nvim
  become_user: "{{ user.name }}"
  file:
    path: "/home/{{ user.name }}/.config/nvim"
    state: directory

- name: create ~/.config/nvim/colors
  become_user: "{{ user.name }}"
  file:
    path: "/home/{{ user.name }}/.config/nvim/colors"
    state: directory


# Files
- name: copy .xinitrc
  become_user: "{{ user.name }}"
  copy:
    src: .xinitrc
    dest: "/home/{{ user.name }}/.xinitrc"

- name: copy .inputrc
  become_user: "{{ user.name }}"
  copy:
    src: .inputrc
    dest: "/home/{{ user.name }}/.inputrc"

- name: copy .gtkrc-2.0
  become_user: "{{ user.name }}"
  copy:
    src: .gtkrc-2.0
    dest: "/home/{{ user.name }}/.gtkrc-2.0"

- name: copy gtk-3 settings.ini
  become_user: "{{ user.name }}"
  copy:
    src: .config/gtk-3.0/settings.ini
    dest: "/home/{{ user.name }}/.config/gtk-3.0/settings.ini"

- name: copy .config/nvim/init.vim
  become_user: "{{ user.name }}"
  copy:
    src: .config/nvim/init.vim
    dest: "/home/{{ user.name }}/.config/nvim/init.vim"

- name: copy .config/nvim/colors/oceanics.vim
  become_user: "{{ user.name }}"
  copy:
    src: .config/nvim/colors/oceanics.vim
    dest: "/home/{{ user.name }}/.config/nvim/colors/oceanics.vim"

- name: copy wallpaper
  become_user: "{{ user.name }}"
  copy:
    src: Images/wallpaper.jpg
    dest: "/home/{{ user.name }}/Images/wallpaper.jpg"

- name: copy .Xresources
  become_user: "{{ user.name }}"
  template:
    src: .Xresources.j2
    dest: "/home/{{ user.name }}/.Xresources"

- name: copy .bashrc
  become_user: "{{ user.name }}"
  template:
    src: .bashrc.j2
    dest: "/home/{{ user.name }}/.bashrc"

- name: copy chromium-flags.conf
  become_user: "{{ user.name }}"
  template:
    src: .config/chromium-flags.conf.j2
    dest: "/home/{{ user.name }}/.config/chromium-flags.conf"

- name: copy .config/alacritty/alacritty.yml
  become_user: "{{ user.name }}"
  template:
    src: .config/alacritty/alacritty.yml.j2
    dest: "/home/{{ user.name }}/.config/alacritty/alacritty.yml"

- name: copy .eslintrc.js
  become_user: "{{ user.name }}"
  copy:
    src: .eslintrc.js
    dest: "/home/{{ user.name }}/.eslintrc.js"
