- name: copy dotfiles
  become_user: "{{ user.name }}"
  copy:
    src: files/
    dest: "/home/{{ user.name }}/"

- name: set executable permissions for files in ~/.local/bin
  become_user: "{{ user.name }}"
  file:
    path: "/home/{{ user.name }}/.local/bin"
    mode: a+x

- name: .gtkrc-2.0
  become_user: "{{ user.name }}"
  template:
    src: .gtkrc-2.0.j2
    dest: "/home/{{ user.name }}/.gtkrc-2.0"

- name: gtk-3 settings.ini
  become_user: "{{ user.name }}"
  template:
    src: settings.ini.j2
    dest: "/home/{{ user.name }}/.config/gtk-3.0/settings.ini"

- name: .Xresources
  become_user: "{{ user.name }}"
  template:
    src: .Xresources.j2
    dest: "/home/{{ user.name }}/.Xresources"

- name: chromium-flags.conf
  become_user: "{{ user.name }}"
  template:
    src: chromium-flags.conf.j2
    dest: "/home/{{ user.name }}/.config/chromium-flags.conf"

- name: alacritty.yml
  become_user: "{{ user.name }}"
  template:
    src: alacritty.yml.j2
    dest: "/home/{{ user.name }}/.config/alacritty/alacritty.yml"

- name: create vim plug directory
  become_user: "{{ user.name }}"
  file:
    path: "/home/{{ user.name }}/.local/share/nvim/site/autoload"
    state: directory

- name: download vim plug
  become_user: "{{ user.name }}"
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "/home/{{ user.name }}/.local/share/nvim/site/autoload/plug.vim"

