---
- name: create a user
  user:
    name: "{{ user.name }}"
    groups: wheel
    create_home: yes
    password: "{{ user_pass|password_hash('sha512') }}"
    update_password: on_create
    state: present

- name: copy dotfiles
  become_user: "{{ user.name }}"
  copy:
    src: dotfiles
    dest: "/home/{{ user.name }}"

- name: copy sudoers
  copy:
    src: sudoers
    dest: /etc/sudoers
    mode: 440
    validate: "visudo -cf %s"
