---
- name: create a user
  user:
    name: "{{ user.name }}"
    groups: wheel
    create_home: yes
    update_password: on_create
    state: present

- name: copy sudoers
  copy:
    src: sudoers
    dest: /etc/sudoers
    mode: 440
    validate: "visudo -cf %s"
