---
- name: create a user
  user:
    name: "{{ item.name }}"
    groups: "{{ item.groups }}"
    create_home: yes
    update_password: on_create
    state: present
  loop: "{{ users }}"

- name: copy sudoers
  copy:
    src: sudoers
    dest: /etc/sudoers
    mode: 440
    validate: "visudo -cf %s"
