- name: create directory for global node_modules
  become_user: "{{ item.name }}"
  file:
    path: "/home/{{ item.name }}/.node_global"
    state: directory
  loop: "{{ users }}"

- name: install prettier
  command: yarn add prettier
  become_user: "{{ item.name }}"
  args:
    chdir: "/home/{{ item.name }}/.node_global"
    creates: "/home/{{ item.name }}/.node_global/node_modules/.bin/prettier"
  loop: "{{ users }}"

- name: install eslint
  command: yarn add eslint
  become_user: "{{ item.name }}"
  args:
    chdir: "/home/{{ item.name }}/.node_global"
    creates: "/home/{{ item.name }}/.node_global/node_modules/.bin/eslint"
  loop: "{{ users }}"
