---
- name: copy keyboard config file
  copy:
    src: 00-keyboard.conf
    dest: /etc/X11/xorg.conf.d/00-keyboard.conf

- name: copy mouse config file
  copy:
    src: 10-mouse.conf
    dest: /etc/X11/xorg.conf.d/10-mouse.conf

- name: copy intel config file
  copy:
    src: 20-intel.conf
    dest: /etc/X11/xorg.conf.d/20-intel.conf
  when: video == "intel"

- name: copy amd config file
  copy:
    src: 20-amdgpu.conf
    dest: /etc/X11/xorg.conf.d/20-amdgpu.conf
  when: video == "amd"
