- name: copy firejail config
  copy:
    src: firejail.config
    dest: /etc/firejail/firejail.config

- name: jail firefox
  file:
    src: /usr/bin/firejail
    dest: /usr/local/bin/firefox
    state: link

- name: jail firefox-developer-edition
  file:
    src: /usr/bin/firejail
    dest: /usr/local/bin/firefox-developer-edition
    state: link

- name: jail chromium
  file:
    src: /usr/bin/firejail
    dest: /usr/local/bin/chromium
    state: link

# - name: jail node
#   file:
#     src: /usr/bin/firejail
#     dest: /usr/local/bin/node
#     state: link

# - name: jail npm
#   file:
#     src: /usr/bin/firejail
#     dest: /usr/local/bin/npm
#     state: link

# - name: jail npx
#   file:
#     src: /usr/bin/firejail
#     dest: /usr/local/bin/npx
#     state: link

# - name: jail yarn
#   file:
#     src: /usr/bin/firejail
#     dest: /usr/local/bin/yarn
#     state: link

- name: jail telegram-desktop
  file:
    src: /usr/bin/firejail
    dest: /usr/local/bin/telegram-desktop
    state: link

- name: jail code
  file:
    src: /usr/bin/firejail
    dest: /usr/local/bin/code
    state: link
