---
- name: install packages
  pacman:
    update_cache: yes
    name:
      - alacritty
      - git
      - sudo

      # xorg
      - xorg-server
      - xorg-xinit

      # interface
      - i3-gaps
      - i3status
      - i3blocks
      - rofi
      - compton
      - feh

      # browsers
      - chromium
      - firefox

      # editors
      - neovim

      # fonts
      - ttf-dejavu
      - ttf-roboto
      - noto-fonts
      - ttf-liberation
      - ttf-ubuntu-font-family
      - ttf-anonymous-pro
      - ttf-fira-mono
      - ttf-fira-code
      - ttf-freefont
      - adobe-source-code-pro-fonts
      - otf-font-awesome

      # utils
      - fzf
      - ack
      - bash-completion
      - sysstat
      - acpi
      - alsa-utils
      - dhcpcd

      # dev
      - nodejs
      - npm
      - yarn

      # other
      - firejail
    state: present
