---
- name: install packages
  pacman:
    # update_cache: yes
    name:
      - alacritty
      - git
      - openssh
      - thunar

      # xorg
      - xorg-server
      - xorg-xinit
      - xorg-xsetroot

      # interface
      - bspwm
      - sxhkd
      - picom
      - dzen2
      - rofi
      - feh
      - gnome-themes-extra

      # browsers
      - chromium
      - firefox
      - firefox-developer-edition

      # editors
      - neovim
      - vim

      # fonts
      - noto-fonts
      - ttf-dejavu
      - ttf-roboto
      - ttf-liberation
      - ttf-ubuntu-font-family
      - ttf-freefont

      # utils
      - fzf
      - ack
      - fd
      - bash-completion
      - sysstat
      - alsa-utils

      # network
      - dhcpcd
      - netctl
      - wireless_tools
      - iw
      - wpa_supplicant
      - openvpn

      # audio
      - pulseaudio
      - pulseaudio-bluetooth

      # video
      - mpv
      - youtube-dl

      # viewers
      - atril

      # photo
      - gimp
      - scrot
      - gpick

      # dev
      - nodejs
      - npm
      - yarn
      - docker
      - docker-compose
      - gcc
      - clang
      - base-devel
      - postgresql

      # other
      - unzip
      - firejail
      - vifm
      - ranger
      - man
      - dialog
      - xclip
      - bluez
      - bluez-utils
    state: present

- name: install intel video
  pacman:
    # update_cache: yes
    name:
      - xf86-video-intel
    state: present
  when: video == "intel"

- name: install amd video
  pacman:
    # update_cache: yes
    name:
      - xf86-video-amdgpu
    state: present
  when: video == "amd"

- name: install acpi
  pacman:
    # update_cache: yes
    name:
      - acpi
    state: present
  when: battery == true

- name: install xbacklight
  pacman:
    # update_cache: yes
    name:
      - xorg-xbacklight
    state: present
  when: backlight == true

- include: aur.yml
- include: firejail.yml
