---
- name: install packages
  pacman:
    update_cache: yes
    name:
      - alacritty
      - git
      - thunar

      # xorg
      - xorg-server
      - xorg-xinit
      - xorg-xbacklight

      # interface
      - bspwm
      - sxhkd
      - picom
      - rofi
      - feh
      - gnome-themes-extra

      # browsers
      - chromium
      - firefox

      # editors
      - neovim

      # fonts
      - ttf-dejavu
      - ttf-roboto
      - noto-fonts
      - ttf-liberation
      - ttf-ubuntu-font-family
      - ttf-anonymous-pro
      - ttf-fira-mono
      - ttf-fira-code
      - ttf-freefont
      - adobe-source-code-pro-fonts
      - otf-font-awesome

      # utils
      - fzf
      - ack
      - bash-completion
      - sysstat
      - acpi
      - alsa-utils
      - dhcpcd

      # dev
      - nodejs
      - npm
      - yarn
      - docker
      - docker-compose

      # other
      - firejail
      - vifm
      - man
    state: present

- name: install intel video
  pacman:
    update_cache: yes
    name:
      - xf86-video-intel
    state: present
  when: video == "intel"

- name: install amd video
  pacman:
    update_cache: yes
    name:
      - xf86-video-amdgpu
    state: present
  when: video == "amd"

- name: jail node
  file:
    src: /usr/bin/firejail
    dest: /usr/local/bin/node
    state: link

- name: jail npm
  file:
    src: /usr/bin/firejail
    dest: /usr/local/bin/npm
    state: link

- name: jail yarn
  file:
    src: /usr/bin/firejail
    dest: /usr/local/bin/yarn
    state: link

- name: jail neovim
  file:
    src: /usr/bin/firejail
    dest: /usr/local/bin/nvim
    state: link
