---
# Node
- name: copy node firejail profile
  become_user: "{{ user.name }}"
  copy:
    src: node.profile
    dest: "/home/{{ user.name }}/.config/firejail/node.profile"

- name: jail node
  file:
    src: /usr/bin/firejail
    dest: /usr/local/bin/node
    state: link

# NPM
- name: copy npm firejail profile
  become_user: "{{ user.name }}"
  copy:
    src: npm.profile
    dest: "/home/{{ user.name }}/.config/firejail/npm.profile"

- name: jail npm
  file:
    src: /usr/bin/firejail
    dest: /usr/local/bin/npm
    state: link

# Yarn
- name: copy yarn firejail profile
  become_user: "{{ user.name }}"
  copy:
    src: yarn.profile
    dest: "/home/{{ user.name }}/.config/firejail/yarn.profile"

- name: jail yarn
  file:
    src: /usr/bin/firejail
    dest: /usr/local/bin/yarn
    state: link
