---
- name: alacritty
  pacman:
    name:
      - alacritty
    state: present

- name: copy alacritty config
  become_user: "{{ user.name }}"
  copy:
    src: alacritty.yml
    dest: ~/.config/alacritty/alacritty.yml
