---
- name: families
  pacman:
    name:
      - ttf-dejavu
      - ttf-roboto
      - noto-fonts
      - ttf-liberation
      - ttf-ubuntu-font-family
    state: present

- name: monospace
  pacman:
    name:
      - ttf-anonymous-pro
      - ttf-fira-mono
      - ttf-fira-code
      - ttf-freefont
      - adobe-source-code-pro-fonts
    state: present

- name: glyphs
  pacman:
    name:
      - otf-font-awesome
    state: present
