---
- name: Copy PT fonts
  copy:
    src: "{{ item }}"
    dest: "/usr/share/fonts/paratype/"
  with_fileglob:
    - "files/paratype/*"

- name: Copy Material Design fonts
  copy:
    src: materialdesignicons-webfont.ttf
    dest: "/usr/share/fonts/materialdesignicons/"
